# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 01:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admon_nombre', models.CharField(max_length=40)),
                ('Admon_tel', models.CharField(max_length=15)),
                ('Admon_correo', models.EmailField(max_length=254)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Defunciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_apoyo', models.DateField(default=datetime.date.today)),
                ('Apoyo', models.IntegerField()),
                ('Recipiente_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_evento', models.DateField()),
                ('Lugar_evento', models.CharField(max_length=100)),
                ('Hora_evento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.date.today)),
                ('Diagnostico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Minutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_reunion', models.DateField()),
                ('Total_donacionesmon', models.IntegerField()),
                ('Valor_donacionesesp', models.IntegerField()),
                ('Duracion_reunion', models.CharField(max_length=15)),
                ('Pacientes_beneficiados', models.IntegerField()),
                ('Observaciones', models.TextField()),
                ('Asistentes', models.ManyToManyField(to='bases.Administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente_nombre', models.CharField(max_length=40)),
                ('Paciente_apellido', models.CharField(max_length=50)),
                ('Paciente_fnacimiento', models.DateField()),
                ('Paciente_diagnostico', models.CharField(max_length=200)),
                ('Paciente_clinica', models.CharField(max_length=50)),
                ('Tutor_Padre', models.CharField(max_length=50)),
                ('Paciente_contacto', models.CharField(blank=True, max_length=15)),
                ('Estado_salud', models.CharField(choices=[('RE', 'Remision'), ('TR', 'En Tratamiento'), ('DEP', 'Fallecido')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_nombre', models.CharField(max_length=40)),
                ('Personal_apellidos', models.CharField(max_length=50)),
                ('Personal_funcion', models.CharField(max_length=60)),
                ('Personal_tel', models.CharField(max_length=15)),
                ('Personal_correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento_Apoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_entrega', models.DateField(default=datetime.date.today)),
                ('Apoyo_Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Paciente')),
                ('Donacion_especie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Donaciones_Especie')),
                ('Donacion_monetaria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Donaciones_Monetarias')),
            ],
        ),
        migrations.AddField(
            model_name='historial_medico',
            name='Paciente_hm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Paciente'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='Personal_evento',
            field=models.ManyToManyField(to='bases.Personal'),
        ),
        migrations.AddField(
            model_name='defunciones',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Paciente'),
        ),
    ]
